#!/bin/bash
set -e

# TicketsCAD Docker Entrypoint
# Auto-configures database connection on first run

MYSQL_CONFIG="/var/www/html/incs/mysql.inc.php"

# Wait for database to be ready
if [ -n "$DB_HOST" ]; then
    echo "TicketsCAD: Waiting for database at $DB_HOST..."
    # Write a temp PHP script to test connection (avoids shell escaping issues)
    cat > /tmp/dbtest.php << 'DBTEST'
<?php
$host = getenv('DB_HOST') ?: 'db';
$user = getenv('DB_USER') ?: 'tickets';
$pass = getenv('DB_PASS') ?: 'tickets';
$db   = getenv('DB_NAME') ?: 'tickets';
$c = @new mysqli($host, $user, $pass, $db);
if ($c->connect_error) { exit(1); }
echo 'OK';
$c->close();
DBTEST
    for i in $(seq 1 60); do
        if php /tmp/dbtest.php 2>/dev/null | grep -q OK; then
            echo "TicketsCAD: Database is ready."
            break
        fi
        if [ $i -eq 60 ]; then
            echo "TicketsCAD: WARNING — Database not reachable after 120 seconds. Starting Apache anyway."
        fi
        echo "TicketsCAD: Waiting for database... ($i/60)"
        sleep 2
    done
    rm -f /tmp/dbtest.php
fi

# Write MySQL config if environment variables are set and config doesn't exist or is default
if [ -n "$DB_HOST" ] && [ -n "$DB_USER" ]; then
    echo "TicketsCAD: Writing database configuration..."
    cat > "$MYSQL_CONFIG" << PHPEOF
<?php
// Auto-generated by Docker entrypoint
// Modify via environment variables: DB_HOST, DB_USER, DB_PASS, DB_NAME, DB_PREFIX
\$mysql_host   = '${DB_HOST}';
\$mysql_user   = '${DB_USER:-tickets}';
\$mysql_passwd = '${DB_PASS:-tickets}';
\$mysql_db     = '${DB_NAME:-tickets}';
\$mysql_prefix = '${DB_PREFIX:-}';
PHPEOF
    chown www-data:www-data "$MYSQL_CONFIG"
    chmod 640 "$MYSQL_CONFIG"
    echo "TicketsCAD: Database config written."
fi

# Auto-install if database is empty (no settings table)
if [ "${AUTO_INSTALL:-true}" = "true" ] && [ -n "$DB_HOST" ]; then
    TABLE_EXISTS=$(php /var/www/html/docker-autoinstall.php check 2>/dev/null)

    if [ "$TABLE_EXISTS" = "no" ]; then
        echo "TicketsCAD: No tables found. Running auto-install..."
        php /var/www/html/docker-autoinstall.php install 2>&1
        echo "TicketsCAD: Login with ${ADMIN_USER:-admin} / ${ADMIN_PASS:-admin}"
    elif [ "$TABLE_EXISTS" = "error" ]; then
        echo "TicketsCAD: WARNING — Could not check database. Starting Apache anyway."
    else
        echo "TicketsCAD: Database already initialized."
    fi
fi

# ── Persistent storage setup ──

# Ensure uploads directory exists and is writable
mkdir -p /var/www/html/uploads
chown www-data:www-data /var/www/html/uploads
chmod 775 /var/www/html/uploads

# Set up tile cache directory (persistent volume)
TILE_CACHE_DIR="/var/www/html/_tile_cache"
mkdir -p "$TILE_CACHE_DIR"
chown www-data:www-data "$TILE_CACHE_DIR"
chmod 775 "$TILE_CACHE_DIR"

# Symlink tile cache if the app expects it elsewhere
if [ -d /var/www/html/tile_cache ] && [ ! -L /var/www/html/tile_cache ]; then
    rm -rf /var/www/html/tile_cache
fi
if [ ! -e /var/www/html/tile_cache ]; then
    ln -sf "$TILE_CACHE_DIR" /var/www/html/tile_cache
fi

# Persist the mysql config across container restarts
CONFIG_PERSIST="/var/www/html/incs/config_persist"
mkdir -p "$CONFIG_PERSIST"
if [ -f "$CONFIG_PERSIST/mysql.inc.php" ] && [ -n "$DB_HOST" ]; then
    # Config exists in persistent volume — use it
    cp "$CONFIG_PERSIST/mysql.inc.php" /var/www/html/incs/mysql.inc.php
    chown www-data:www-data /var/www/html/incs/mysql.inc.php
    echo "TicketsCAD: Restored config from persistent volume."
elif [ -f /var/www/html/incs/mysql.inc.php ]; then
    # Save current config to persistent volume
    cp /var/www/html/incs/mysql.inc.php "$CONFIG_PERSIST/mysql.inc.php"
    echo "TicketsCAD: Saved config to persistent volume."
fi

echo "TicketsCAD: Starting Apache..."
exec "$@"
