#!/bin/bash
set -e

# TicketsCAD Docker Entrypoint
# Auto-configures database connection on first run

MYSQL_CONFIG="/var/www/html/incs/mysql.inc.php"

# Wait for database to be ready
if [ -n "$DB_HOST" ]; then
    echo "TicketsCAD: Waiting for database at $DB_HOST..."
    for i in $(seq 1 30); do
        if php -r "
            \$c = @new mysqli('$DB_HOST', '${DB_USER:-tickets}', '${DB_PASS:-tickets}', '${DB_NAME:-tickets}');
            if (\$c->connect_error) exit(1);
            echo 'OK';
            \$c->close();
        " 2>/dev/null | grep -q OK; then
            echo "TicketsCAD: Database is ready."
            break
        fi
        echo "TicketsCAD: Waiting for database... ($i/30)"
        sleep 2
    done
fi

# Write MySQL config if environment variables are set and config doesn't exist or is default
if [ -n "$DB_HOST" ] && [ -n "$DB_USER" ]; then
    echo "TicketsCAD: Writing database configuration..."
    cat > "$MYSQL_CONFIG" << PHPEOF
<?php
// Auto-generated by Docker entrypoint
// Modify via environment variables: DB_HOST, DB_USER, DB_PASS, DB_NAME, DB_PREFIX
\$mysql_host   = '${DB_HOST}';
\$mysql_user   = '${DB_USER:-tickets}';
\$mysql_passwd = '${DB_PASS:-tickets}';
\$mysql_db     = '${DB_NAME:-tickets}';
\$mysql_prefix = '${DB_PREFIX:-}';
PHPEOF
    chown www-data:www-data "$MYSQL_CONFIG"
    chmod 640 "$MYSQL_CONFIG"
    echo "TicketsCAD: Database config written."
fi

# Auto-install if database is empty (no settings table)
if [ "${AUTO_INSTALL:-true}" = "true" ] && [ -n "$DB_HOST" ]; then
    TABLE_EXISTS=$(php -r "
        \$c = @new mysqli('$DB_HOST', '${DB_USER:-tickets}', '${DB_PASS:-tickets}', '${DB_NAME:-tickets}');
        if (\$c->connect_error) { echo 'error'; exit; }
        \$r = \$c->query('SHOW TABLES LIKE \"settings\"');
        echo \$r && \$r->num_rows > 0 ? 'yes' : 'no';
        \$c->close();
    " 2>/dev/null)

    if [ "$TABLE_EXISTS" = "no" ]; then
        echo "TicketsCAD: No tables found. Running auto-install..."
        # Use the installer in CLI mode
        php -r "
            require_once '/var/www/html/incs/compat.inc.php';
            require_once '/var/www/html/incs/db.inc.php';
            require_once '/var/www/html/incs/security.inc.php';

            // Source the installer schema
            require_once '/var/www/html/incs/install_schema.inc.php';

            // Load installer functions
            \$installerCode = file_get_contents('/var/www/html/install.php');

            // Connect
            \$mysqli = new mysqli('$DB_HOST', '${DB_USER:-tickets}', '${DB_PASS:-tickets}', '${DB_NAME:-tickets}');
            if (\$mysqli->connect_error) {
                echo 'Database connection failed: ' . \$mysqli->connect_error . PHP_EOL;
                exit(1);
            }

            // Create tables from schema
            foreach (\$INSTALL_SCHEMA_TABLES as \$name => \$sql) {
                if (!\$mysqli->query(\$sql)) {
                    echo 'Warning creating ' . \$name . ': ' . \$mysqli->error . PHP_EOL;
                } else {
                    echo 'Created table: ' . \$name . PHP_EOL;
                }
            }

            // Seed data
            foreach (\$INSTALL_SCHEMA_SEED as \$sql) {
                \$mysqli->query(\$sql);
            }

            // Create admin user
            \$adminUser = '${ADMIN_USER:-admin}';
            \$adminPass = hash_password('${ADMIN_PASS:-admin}');
            \$adminName = '${ADMIN_NAME:-Super Administrator}';
            \$mysqli->query(\"DELETE FROM user WHERE id = 1\");
            \$mysqli->query(\"INSERT INTO user (id, user, passwd, info, level, status, open_at, sort_desc, reporting) VALUES (1, '\" . \$mysqli->real_escape_string(\$adminUser) . \"', '\" . \$mysqli->real_escape_string(\$adminPass) . \"', '\" . \$mysqli->real_escape_string(\$adminName) . \"', 0, 'approved', 'd', 1, 0)\");

            // Create guest user
            \$guestPass = md5('guest');
            \$mysqli->query(\"INSERT IGNORE INTO user (id, user, passwd, info, level, status, open_at, sort_desc, reporting) VALUES (2, 'guest', '\" . \$mysqli->real_escape_string(\$guestPass) . \"', 'Guest', 3, 'approved', 'd', 1, 0)\");

            // Set version
            \$mysqli->query(\"INSERT INTO settings (\" . chr(96) . \"key\" . chr(96) . \", \" . chr(96) . \"value\" . chr(96) . \") VALUES ('_version', '3.44.1') ON DUPLICATE KEY UPDATE \" . chr(96) . \"value\" . chr(96) . \" = '3.44.1'\");

            \$mysqli->close();
            echo 'Auto-install complete.' . PHP_EOL;
        " 2>&1 || echo "TicketsCAD: Auto-install had warnings (check logs)"
        echo "TicketsCAD: Installation finished. Login with ${ADMIN_USER:-admin} / ${ADMIN_PASS:-admin}"
    else
        echo "TicketsCAD: Database already initialized."
    fi
fi

echo "TicketsCAD: Starting Apache..."
exec "$@"
