<?php
/**
 * CSV Report Downloader for Tickets CAD
 *
 * Fetches the same HTML report generated by ajax/reports.php, extracts
 * all <table> data, and streams it as a CSV file. This avoids duplicating
 * the 2400+ lines of report SQL in ajax/reports.php — we just convert
 * the rendered HTML tables to CSV.
 *
 * 3/14/2026 - New file
 */
require_once('./incs/functions.inc.php');

$report      = isset($_GET['report'])       ? sanitize_string($_GET['report'])       : '';
$func        = isset($_GET['func'])         ? sanitize_string($_GET['func'])         : '';
$date        = isset($_GET['date'])         ? sanitize_string($_GET['date'])         : '';
$ticksel     = isset($_GET['ticksel'])      ? sanitize_string($_GET['ticksel'])      : '';
$respsel     = isset($_GET['respsel'])      ? sanitize_string($_GET['respsel'])      : '';
$organisation = isset($_GET['organisation']) ? sanitize_string($_GET['organisation']) : '';
$startdate   = isset($_GET['startdate'])    ? sanitize_string($_GET['startdate'])    : '';
$enddate     = isset($_GET['enddate'])      ? sanitize_string($_GET['enddate'])      : '';
$title       = isset($_GET['title'])        ? sanitize_string($_GET['title'])        : '';
$httpuser    = get_variable('httpuser');
$httppwd     = get_variable('httppwd');

// ---- Build URL to fetch the HTML report ----

function curPageURL() {
    $pageURL = 'http';
    if (array_key_exists("HTTPS", $_SERVER) && $_SERVER["HTTPS"] == "on") { $pageURL .= "s"; }
    $pageURL .= "://";
    $uri = rtrim(dirname($_SERVER['PHP_SELF']), '/\\');
    if ($_SERVER["SERVER_PORT"] != "80") {
        $pageURL .= $_SERVER["SERVER_NAME"] . ":" . $_SERVER["SERVER_PORT"] . $uri;
    } else {
        $pageURL .= $_SERVER["SERVER_NAME"] . $uri;
    }
    return $pageURL;
}

$serverpath = curPageURL();
$randomnumber = rand(0, 9999999);
$url = $serverpath . "/ajax/reports.php?"
    . "report=" . urlencode($report)
    . "&func=" . urlencode($func)
    . "&date=" . urlencode($date)
    . "&tick_sel=" . urlencode($ticksel)
    . "&resp_sel=" . urlencode($respsel)
    . "&organisation=" . urlencode($organisation)
    . "&startdate=" . urlencode($startdate)
    . "&enddate=" . urlencode($enddate)
    . "&dohtml=true&version=$randomnumber";

// ---- Fetch HTML ----

$thePage = '';
if (function_exists("curl_init")) {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 20);
    if (($httpuser != "") && ($httppwd != "")) {
        curl_setopt($ch, CURLOPT_USERPWD, $httpuser . ":" . $httppwd);
    }
    $thePage = curl_exec($ch);
    curl_close($ch);
} else {
    if ($fp = fopen($url, "r")) {
        while (!feof($fp)) { $thePage .= fgets($fp, 4096); }
        fclose($fp);
    }
}

if (empty($thePage)) {
    http_response_code(500);
    header('Content-Type: text/plain');
    echo 'Error: Could not retrieve report data.';
    exit;
}

// ---- Parse HTML tables into CSV rows ----

// Suppress DOMDocument warnings for malformed HTML
libxml_use_internal_errors(true);

$doc = new DOMDocument();
$doc->loadHTML('<?xml encoding="UTF-8">' . $thePage);
libxml_clear_errors();

$tables = $doc->getElementsByTagName('table');
$csv_rows = array();

foreach ($tables as $table) {
    $rows = $table->getElementsByTagName('tr');
    foreach ($rows as $row) {
        $csv_row = array();
        // Check both TH and TD cells
        $cells = $row->getElementsByTagName('th');
        if ($cells->length == 0) {
            $cells = $row->getElementsByTagName('td');
        } else {
            // Row might have a mix of TH and TD — get all children
            $all_cells = array();
            foreach ($row->childNodes as $child) {
                if ($child->nodeName === 'th' || $child->nodeName === 'td') {
                    $all_cells[] = $child;
                }
            }
            $cells = $all_cells;
        }
        foreach ($cells as $cell) {
            // Get text content, clean whitespace
            $text = trim(preg_replace('/\s+/', ' ', $cell->textContent));
            $csv_row[] = $text;
        }
        if (!empty($csv_row)) {
            $csv_rows[] = $csv_row;
        }
    }
    // Add blank row between tables
    if (!empty($csv_rows)) {
        $csv_rows[] = array('');
    }
}

// Remove trailing blank row
if (!empty($csv_rows) && $csv_rows[count($csv_rows) - 1] === array('')) {
    array_pop($csv_rows);
}

// Remove leading blank rows
while (!empty($csv_rows) && (count($csv_rows[0]) === 1 && trim($csv_rows[0][0]) === '')) {
    array_shift($csv_rows);
}

// ---- Build filename ----

$reportname = base64_decode($title);
$reportname = str_replace(array(" ", ","), '_', $reportname);
if (empty($reportname)) { $reportname = 'report'; }

// ---- Output CSV ----

header('Content-Type: text/csv; charset=UTF-8');
header('Content-Disposition: attachment; filename=' . $reportname . '.csv');
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
header('Expires: 0');

$fp = fopen('php://output', 'w');
foreach ($csv_rows as $row) {
    fputcsv($fp, $row);
}
fclose($fp);
exit;
