<?php
	error_reporting(E_ALL);				// 2/3/09 

	$version = "2.10 D beta";			// see usage below 1/30/09

	$filename = './incs/mysql.inc.php';
	
	if (file_exists($filename)) {
	    echo "The file $filename exists\n\n";
		} 
	else {
	    echo "The file $filename does not exist\n\n";
		}
	$handle = @fopen($filename, "r");
	$searches = array("'", ";");

	if ($handle) {
	    while (!feof($handle)) {
	        $buffer = fgets($handle, 4096);
	        if ($buffer{0}=="\t"){					// $string{0}; -- str_replace ("'", "",  trim($in_ary[1]))

//	        	echo $buffer;
	        	$in_ary = explode ("=", $buffer);
	        	if( count($in_ary)==2) {
	
		        	switch (trim($in_ary[0])) {
					case "\$mysql_host":
					    $mysql_host =  str_replace ($searches, "",  trim($in_ary[1]));
					    echo  $mysql_host  . "\n";
					    break;
					case "\$mysql_db":
					    $mysql_db = str_replace ($searches, "",  trim($in_ary[1])) ;
					    echo  $mysql_db  . "\n";
					    break;
					case "\$mysql_user":
					    $mysql_user = str_replace ($searches, "",  trim($in_ary[1])) ;
					    echo  $mysql_user  . "\n";
					    break;
					case "\$mysql_passwd":
					    $mysql_passwd = str_replace ($searches, "",  trim($in_ary[1])) ;
					    echo  $mysql_passwd  . "\n";
					    break;
					case "\$mysql_prefix":
					    $mysql_prefix = str_replace ($searches, "",  trim($in_ary[1])) ;
					    echo  $mysql_prefix  . "\n";
					    break;
					default:
					    echo "error - error - error:" . $in_ary[0];
					}
		    	}
		    }
		}
	   fclose($handle);
	   }
//	/* generated by 'install.php' Wed, 25 Feb 2009 08:13:55 -0600 */
//	$mysql_host 	= 'localhost';
//	$mysql_db 		= 'test_10_c';
////	$mysql_db 		= 'ari';
//	$mysql_user 	= 'root';
//	$mysql_passwd 	= '';
//	$mysql_prefix 	= '';

?>