<?php
	/* generated by 'install.php' Thu, 06 Nov 2008 18:23:28 -0600 */
	$mysql_host 	= 'localhost';
	$mysql_db 		= 'tickets_2_9_a';
	$mysql_user 	= 'root';
	$mysql_passwd 	= '';
	$mysql_prefix 	= 'ZZ_';
?>