<?php
	/* generated by 'install.php' Sun, 12 Oct 2008 10:11:41 -0500 */
	$mysql_host 	= 'localhost';
	$mysql_db 		= 'tickets_2_9';
	$mysql_user 	= 'root';
	$mysql_passwd 	= '';
	$mysql_prefix 	= '';
?>