<?php
	/* generated by 'install.php' Wed, 25 Feb 2009 08:13:55 -0600 */
	$mysql_host 	= 'localhost';
	$mysql_db 		= 'test_10_e';
//	$mysql_db 		= 'ari';
	$mysql_user 	= 'root';
	$mysql_passwd 	= '';
	$mysql_prefix 	= '';
?>