<?php
	/* generated by 'install.php' Thu, 21 Apr 2011 14:02:47 +0000 */
	$mysql_host 	= 'localhost';
	$mysql_db 		= 'tickets_apostrophe';
	$mysql_user 	= 'root';
	$mysql_passwd 	= '';
	$mysql_prefix 	= 'pre_';
?>